output.elasticsearch:
  hosts: ["http://es01:9200"]
setup.kibana:
  host: "http://kibana:5601"
metricbeat.modules:
  - module: kafka
    metricsets:
     - partition
     - consumergroup
    period: 10s
    hosts: ["master-1:9094", "worker-1:9094", "worker-2:9094"]
  - module: kafka
    metricsets:
      - broker
      - producer
      - consumer
    period: 10s
    hosts: ["master-1:8778", "worker-1:8778", "worker-2:8778"]